### PR TITLE
Quick fix for coroutine robots env reset

### PR DESCRIPTION
**Pull request by Kimapr**
Currently, robots always try to create new global environment when they are loaded from staticdata. This creates problems for coroutine mode robots - globals are reset in the middle execution and the programs crash. It would be possible for players to circumvent this but the execution counter uses globals for counting execution counts. They can't change that code so they can't circumvent this (assuming they don't have access to sources of the mod e.g on a server). This will create guaranteed crash when a robot is unloaded and then loaded again and makes coroutine mode practically unusable.

### CODE REVIEW

**Comment by ac-minetest** [comment]
your fix :
`if not basic_robot.data[name].cor then initSandbox ( name ) end`


the way how things work then: init 1. creates sandbox (if no coroutine present), 2. creates coroutine

question: is it possible that coroutine exists and this would skip sandbox creation in 1. if needed? if you are not 100% sure this could create bug.

Suggestion: this might be better fix, just don't recreate sandbox if we have it already
`if not basic_robot.data[name].sandbox then initSandbox ( name ) end`

i don't even know why would i ever want to recreate sandbox if the robot is already running, just keep it the way it is, now that i think about it...

**Comment by ac-minetest** [comment]
Good find and observation otherwise.

**Comment by Kimapr** [comment]
I agree the suggested fix is better, because this bug also causes non-coroutine robots to forget themselves after being reloaded from staticdata.

**Comment by ac-minetest** [comment]
i did some tests and found out keeping sandbox always is not good idea. For one variables don't reset after you restart robot, so you cant run program from 'fresh start'. So i made it so manual restart resets sandbox but just 'waking up' does not.

**Review by ac-minetest — COMMENTED** [review]
i already did it by adding another parameter like `local function init_robot(obj, resetSandbox)`
and then `if resetSandbox then initSandbox ( name ) end`

then i simply dont reset it on wakeup. Still want to add you as contributor. How i do that?

**Comment by Kimapr** [comment]
I checked the option to allow edits to my fork from maintainers. So you can edit my repo's master branch and add you edits there, then merge this PR.

**Comment by ac-minetest** [comment]
was that good? never did this before. Just used 'resolved conflict' button here, fixed to what it looks like in my version and submitted. Then did 'merge'.

**Pull request merged**
